import { Pokemon, PokemonType } from './types';

export const POKEMON_GEN_1: Pokemon[] = [
  { id: 1, name: 'Bulbizarre', types: [PokemonType.Grass, PokemonType.Poison] },
  { id: 2, name: 'Herbizarre', types: [PokemonType.Grass, PokemonType.Poison] },
  { id: 3, name: 'Florizarre', types: [PokemonType.Grass, PokemonType.Poison] },
  { id: 4, name: 'Salameche', types: [PokemonType.Fire] },
  { id: 5, name: 'Reptincel', types: [PokemonType.Fire] },
  { id: 6, name: 'Dracaufeu', types: [PokemonType.Fire, PokemonType.Flying] },
  { id: 7, name: 'Carapuce', types: [PokemonType.Water] },
  { id: 8, name: 'Carabaffe', types: [PokemonType.Water] },
  { id: 9, name: 'Tortank', types: [PokemonType.Water] },
  { id: 10, name: 'Chenipan', types: [PokemonType.Bug] },
  { id: 11, name: 'Chrysacier', types: [PokemonType.Bug] },
  { id: 12, name: 'Papilusion', types: [PokemonType.Bug, PokemonType.Flying] },
  { id: 13, name: 'Aspicot', types: [PokemonType.Bug, PokemonType.Poison] },
  { id: 14, name: 'Coconfort', types: [PokemonType.Bug, PokemonType.Poison] },
  { id: 15, name: 'Dardargnan', types: [PokemonType.Bug, PokemonType.Poison] },
  { id: 16, name: 'Roucool', types: [PokemonType.Normal, PokemonType.Flying] },
  { id: 17, name: 'Roucoups', types: [PokemonType.Normal, PokemonType.Flying] },
  { id: 18, name: 'Roucarnage', types: [PokemonType.Normal, PokemonType.Flying] },
  { id: 19, name: 'Rattata', types: [PokemonType.Normal] },
  { id: 20, name: 'Rattatac', types: [PokemonType.Normal] },
  { id: 21, name: 'Piafabec', types: [PokemonType.Normal, PokemonType.Flying] },
  { id: 22, name: 'Rapasdepic', types: [PokemonType.Normal, PokemonType.Flying] },
  { id: 23, name: 'Abo', types: [PokemonType.Poison] },
  { id: 24, name: 'Arbok', types: [PokemonType.Poison] },
  { id: 25, name: 'Pikachu', types: [PokemonType.Electric] },
  { id: 26, name: 'Raichu', types: [PokemonType.Electric] },
  { id: 27, name: 'Sabelette', types: [PokemonType.Ground] },
  { id: 28, name: 'Sablaireau', types: [PokemonType.Ground] },
  { id: 29, name: 'Nidoran F', types: [PokemonType.Poison] },
  { id: 30, name: 'Nidorina', types: [PokemonType.Poison] },
  { id: 31, name: 'Nidoqueen', types: [PokemonType.Poison, PokemonType.Ground] },
  { id: 32, name: 'Nidoran M', types: [PokemonType.Poison] },
  { id: 33, name: 'Nidorino', types: [PokemonType.Poison] },
  { id: 34, name: 'Nidoking', types: [PokemonType.Poison, PokemonType.Ground] },
  { id: 35, name: 'Melofee', types: [PokemonType.Fairy] },
  { id: 36, name: 'Melodelfe', types: [PokemonType.Fairy] },
  { id: 37, name: 'Goupix', types: [PokemonType.Fire] },
  { id: 38, name: 'Feunard', types: [PokemonType.Fire] },
  { id: 39, name: 'Rondoudou', types: [PokemonType.Normal, PokemonType.Fairy] },
  { id: 40, name: 'Grodoudou', types: [PokemonType.Normal, PokemonType.Fairy] },
  { id: 41, name: 'Nosferapti', types: [PokemonType.Poison, PokemonType.Flying] },
  { id: 42, name: 'Nosferalto', types: [PokemonType.Poison, PokemonType.Flying] },
  { id: 43, name: 'Mystherbe', types: [PokemonType.Grass, PokemonType.Poison] },
  { id: 44, name: 'Ortide', types: [PokemonType.Grass, PokemonType.Poison] },
  { id: 45, name: 'Rafflesia', types: [PokemonType.Grass, PokemonType.Poison] },
  { id: 46, name: 'Paras', types: [PokemonType.Bug, PokemonType.Grass] },
  { id: 47, name: 'Parasect', types: [PokemonType.Bug, PokemonType.Grass] },
  { id: 48, name: 'Mimitoss', types: [PokemonType.Bug, PokemonType.Poison] },
  { id: 49, name: 'Aeromite', types: [PokemonType.Bug, PokemonType.Poison] },
  { id: 50, name: 'Taupiqueur', types: [PokemonType.Ground] },
  { id: 51, name: 'Triopikeur', types: [PokemonType.Ground] },
  { id: 52, name: 'Miaouss', types: [PokemonType.Normal] },
  { id: 53, name: 'Persian', types: [PokemonType.Normal] },
  { id: 54, name: 'Psykokwak', types: [PokemonType.Water] },
  { id: 55, name: 'Akwakwak', types: [PokemonType.Water] },
  { id: 56, name: 'Ferosinge', types: [PokemonType.Fighting] },
  { id: 57, name: 'Colossinge', types: [PokemonType.Fighting] },
  { id: 58, name: 'Caninos', types: [PokemonType.Fire] },
  { id: 59, name: 'Arcanin', types: [PokemonType.Fire] },
  { id: 60, name: 'Ptitard', types: [PokemonType.Water] },
  { id: 61, name: 'Tetarte', types: [PokemonType.Water] },
  { id: 62, name: 'Tartard', types: [PokemonType.Water, PokemonType.Fighting] },
  { id: 63, name: 'Abra', types: [PokemonType.Psychic] },
  { id: 64, name: 'Kadabra', types: [PokemonType.Psychic] },
  { id: 65, name: 'Alakazam', types: [PokemonType.Psychic] },
  { id: 66, name: 'Machoc', types: [PokemonType.Fighting] },
  { id: 67, name: 'Machopeur', types: [PokemonType.Fighting] },
  { id: 68, name: 'Mackogneur', types: [PokemonType.Fighting] },
  { id: 69, name: 'Chetiflor', types: [PokemonType.Grass, PokemonType.Poison] },
  { id: 70, name: 'Boustiflor', types: [PokemonType.Grass, PokemonType.Poison] },
  { id: 71, name: 'Empiflor', types: [PokemonType.Grass, PokemonType.Poison] },
  { id: 72, name: 'Tentacool', types: [PokemonType.Water, PokemonType.Poison] },
  { id: 73, name: 'Tentacruel', types: [PokemonType.Water, PokemonType.Poison] },
  { id: 74, name: 'Racaillou', types: [PokemonType.Rock, PokemonType.Ground] },
  { id: 75, name: 'Gravalanch', types: [PokemonType.Rock, PokemonType.Ground] },
  { id: 76, name: 'Grolem', types: [PokemonType.Rock, PokemonType.Ground] },
  { id: 77, name: 'Ponyta', types: [PokemonType.Fire] },
  { id: 78, name: 'Galopa', types: [PokemonType.Fire] },
  { id: 79, name: 'Ramoloss', types: [PokemonType.Water, PokemonType.Psychic] },
  { id: 80, name: 'Flagadoss', types: [PokemonType.Water, PokemonType.Psychic] },
  { id: 81, name: 'Magneti', types: [PokemonType.Electric] },
  { id: 82, name: 'Magneton', types: [PokemonType.Electric] },
  { id: 83, name: 'Canarticho', types: [PokemonType.Normal, PokemonType.Flying] },
  { id: 84, name: 'Doduo', types: [PokemonType.Normal, PokemonType.Flying] },
  { id: 85, name: 'Dodrio', types: [PokemonType.Normal, PokemonType.Flying] },
  { id: 86, name: 'Otaria', types: [PokemonType.Water] },
  { id: 87, name: 'Lamantine', types: [PokemonType.Water, PokemonType.Ice] },
  { id: 88, name: 'Tadmorv', types: [PokemonType.Poison] },
  { id: 89, name: 'Grotadmorv', types: [PokemonType.Poison] },
  { id: 90, name: 'Kokiyas', types: [PokemonType.Water] },
  { id: 91, name: 'Crustabri', types: [PokemonType.Water, PokemonType.Ice] },
  { id: 92, name: 'Fantominus', types: [PokemonType.Ghost, PokemonType.Poison] },
  { id: 93, name: 'Spectrum', types: [PokemonType.Ghost, PokemonType.Poison] },
  { id: 94, name: 'Ectoplasma', types: [PokemonType.Ghost, PokemonType.Poison] },
  { id: 95, name: 'Onix', types: [PokemonType.Rock, PokemonType.Ground] },
  { id: 96, name: 'Soporifik', types: [PokemonType.Psychic] },
  { id: 97, name: 'Hypnomade', types: [PokemonType.Psychic] },
  { id: 98, name: 'Krabby', types: [PokemonType.Water] },
  { id: 99, name: 'Krabboss', types: [PokemonType.Water] },
  { id: 100, name: 'Voltorbe', types: [PokemonType.Electric] },
  { id: 101, name: 'Electrode', types: [PokemonType.Electric] },
  { id: 102, name: 'Noeunoeuf', types: [PokemonType.Grass, PokemonType.Psychic] },
  { id: 103, name: 'Noadkoko', types: [PokemonType.Grass, PokemonType.Psychic] },
  { id: 104, name: 'Osselait', types: [PokemonType.Ground] },
  { id: 105, name: 'Ossatueur', types: [PokemonType.Ground] },
  { id: 106, name: 'Kicklee', types: [PokemonType.Fighting] },
  { id: 107, name: 'Tygnon', types: [PokemonType.Fighting] },
  { id: 108, name: 'Excelangue', types: [PokemonType.Normal] },
  { id: 109, name: 'Smogo', types: [PokemonType.Poison] },
  { id: 110, name: 'Smogogo', types: [PokemonType.Poison] },
  { id: 111, name: 'Rhinocorne', types: [PokemonType.Ground, PokemonType.Rock] },
  { id: 112, name: 'Rhinoferos', types: [PokemonType.Ground, PokemonType.Rock] },
  { id: 113, name: 'Leveinard', types: [PokemonType.Normal] },
  { id: 114, name: 'Saquedeneu', types: [PokemonType.Grass] },
  { id: 115, name: 'Kangourex', types: [PokemonType.Normal] },
  { id: 116, name: 'Hypotrempe', types: [PokemonType.Water] },
  { id: 117, name: 'Hypocean', types: [PokemonType.Water] },
  { id: 118, name: 'Poissirene', types: [PokemonType.Water] },
  { id: 119, name: 'Poissoroy', types: [PokemonType.Water] },
  { id: 120, name: 'Stari', types: [PokemonType.Water] },
  { id: 121, name: 'Staross', types: [PokemonType.Water, PokemonType.Psychic] },
  { id: 122, name: 'M. Mime', types: [PokemonType.Psychic, PokemonType.Fairy] },
  { id: 123, name: 'Insecateur', types: [PokemonType.Bug, PokemonType.Flying] },
  { id: 124, name: 'Lippoutou', types: [PokemonType.Ice, PokemonType.Psychic] },
  { id: 125, name: 'Elektek', types: [PokemonType.Electric] },
  { id: 126, name: 'Magmar', types: [PokemonType.Fire] },
  { id: 127, name: 'Scarabrute', types: [PokemonType.Bug] },
  { id: 128, name: 'Tauros', types: [PokemonType.Normal] },
  { id: 129, name: 'Magicarpe', types: [PokemonType.Water] },
  { id: 130, name: 'Leviator', types: [PokemonType.Water, PokemonType.Flying] },
  { id: 131, name: 'Lokhlass', types: [PokemonType.Water, PokemonType.Ice] },
  { id: 132, name: 'Metamorph', types: [PokemonType.Normal] },
  { id: 133, name: 'Evoli', types: [PokemonType.Normal] },
  { id: 134, name: 'Aquali', types: [PokemonType.Water] },
  { id: 135, name: 'Voltali', types: [PokemonType.Electric] },
  { id: 136, name: 'Pyroli', types: [PokemonType.Fire] },
  { id: 137, name: 'Porygon', types: [PokemonType.Normal] },
  { id: 138, name: 'Amonita', types: [PokemonType.Rock, PokemonType.Water] },
  { id: 139, name: 'Amonistar', types: [PokemonType.Rock, PokemonType.Water] },
  { id: 140, name: 'Kabuto', types: [PokemonType.Rock, PokemonType.Water] },
  { id: 141, name: 'Kabutops', types: [PokemonType.Rock, PokemonType.Water] },
  { id: 142, name: 'Ptera', types: [PokemonType.Rock, PokemonType.Flying] },
  { id: 143, name: 'Ronflex', types: [PokemonType.Normal] },
  { id: 144, name: 'Artikodin', types: [PokemonType.Ice, PokemonType.Flying] },
  { id: 145, name: 'Electhor', types: [PokemonType.Electric, PokemonType.Flying] },
  { id: 146, name: 'Sulfura', types: [PokemonType.Fire, PokemonType.Flying] },
  { id: 147, name: 'Minidraco', types: [PokemonType.Dragon] },
  { id: 148, name: 'Draco', types: [PokemonType.Dragon] },
  { id: 149, name: 'Dracolosse', types: [PokemonType.Dragon, PokemonType.Flying] },
  { id: 150, name: 'Mewtwo', types: [PokemonType.Psychic] },
  { id: 151, name: 'Mew', types: [PokemonType.Psychic] },
];

export const RARE_IDS = new Set<number>([3, 6, 9, 94, 130, 142, 143, 144, 145, 146, 149, 150, 151]);

export const findPokemon = (id: number): Pokemon | undefined =>
  POKEMON_GEN_1.find((p) => p.id === id);
